// Generated by probevane. MSW request handlers. Array responses import the
// shared test-fixtures/*.json so the same data flows through the whole chain.
import { http, HttpResponse } from 'msw';
import products from '../../test-fixtures/products.json';

export const handlers = [
  http.get('/api/products', () => HttpResponse.json(products)),
  http.get('/api/products/:id', () => HttpResponse.json({
    "id": 1,
    "name": "sample",
    "priceCents": 0,
    "inStock": true
  })),
];
