// Generated by probevane. MSW node server for vitest. Import + lifecycle in your spec,
// or wire into vitest.setup.ts.
import { setupServer } from 'msw/node';
import { handlers } from './handlers';

export const server = setupServer(...handlers);
