// Federation contract-test templater (MFE Phase C). Pure + deterministic ($0, no
// LLM): given a remote's exposes (and optionally a typed contract source), emit
// the contract-test file CONTENT. Two directions:
//   - remote-side: a compile-time conformance test — the exposed module must
//     satisfy its published interface (catches the remote breaking its own contract).
//   - host-side: a mocked test — the host consumes the federated module against the
//     interface it expects (catches a host/remote drift before runtime).
// When no typed contract is available it falls back to a structural smoke + a note
// to publish types. The scanner decides type-source + file placement; this is the
// string templating only.

export interface ContractType {
  name: string; // exported type, e.g. 'CartContract'
  from: string; // import specifier for the type, e.g. '@mf-types/cart/Cart'
}

/** One generated contract test — filename + full content; typed=false marks the
 *  structural fallback. Emitted by the templaters, written by the scanner/driver. */
export interface ContractFile {
  file: string; // suggested filename (relative)
  content: string;
  typed: boolean; // false = structural fallback (no contract type found)
}

/** `./Cart` → `Cart`, `./ui/Button` → `ui-Button`. */
export function exposeName(key: string): string {
  return key.replace(/^\.\//, '').replace(/\//g, '-') || 'default';
}

const HEADER = '// AUTO-GENERATED by probevane mfe-contract — edit freely; re-run to refresh.';

/** Remote-side: the exposed module must satisfy its contract (compile-time + smoke). */
export function remoteContractTest(
  remote: string,
  exposeKey: string,
  importPath: string,
  contract?: ContractType,
): ContractFile {
  const nm = exposeName(exposeKey);
  const typed = !!contract;
  const lines = [HEADER, `import Exposed from '${importPath}';`];
  if (contract) {
    lines.push(`import type { ${contract.name} } from '${contract.from}';`);
    lines.push(`// Compile-time: exposed module must conform to its published contract.`);
    lines.push(`const _conforms: ${contract.name} = Exposed as ${contract.name};`);
  }
  lines.push(
    `import { describe, it, expect } from 'vitest';`,
    ``,
    `describe('${remote} contract: ${exposeKey}', () => {`,
    `  it('exposes a defined module${typed ? ' that conforms to its contract' : ' (structural — publish a typed contract for stronger checks)'}', () => {`,
    ...(typed ? [`    void _conforms;`] : []),
    `    expect(Exposed === undefined).toBe(false);`,
    `  });`,
    `});`,
    ``,
  );
  return { file: `${nm}.contract.test.ts`, content: lines.join('\n'), typed };
}

/** Host-side: consume the federated module (mocked) against the expected contract. */
export function hostContractTest(
  host: string,
  remote: string,
  exposeKey: string,
  contract?: ContractType,
): ContractFile {
  const nm = exposeName(exposeKey);
  const spec = `${remote}/${nm}`;
  const typed = !!contract;
  const lines = [
    HEADER,
    `import { describe, it, expect, vi } from 'vitest';`,
    `// The remote is federated at runtime — mock its exposed module for the contract test.`,
    `vi.mock('${spec}', () => ({ default: () => null }));`,
    `import Remote from '${spec}';`,
  ];
  if (contract) {
    lines.push(`import type { ${contract.name} } from '${contract.from}';`);
    lines.push(`const _expects: ${contract.name} = Remote as ${contract.name};`);
  }
  lines.push(
    ``,
    `describe('${host} ↔ ${remote} contract: ${exposeKey}', () => {`,
    `  it('consumes the remote against its${typed ? ' contract' : ' shape (structural)'}', () => {`,
    ...(typed ? [`    void _expects;`] : []),
    `    expect(Remote === undefined).toBe(false);`,
    `  });`,
    `});`,
    ``,
  );
  return { file: `${remote}-${nm}.contract.test.ts`, content: lines.join('\n'), typed };
}
