import '@testing-library/jest-dom/vitest';

// probevane:msw-global — MSW server for all tests (generated by probevane)
import { beforeAll, afterEach, afterAll } from 'vitest';
import { server } from './src/mocks/server';
beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());
