// GENERATED by scripts/build-ui.mjs — typed globals for the component
// convention (tags resolve by filename; imports are injected at build time).
declare global {
  const h: typeof import('../runtime.ts').h;
  const Fragment: typeof import('../runtime.ts').Fragment;
  const CostPanel: typeof import('./components/CostPanel.tsx').CostPanel;
  const Drawer: typeof import('./components/Drawer.tsx').Drawer;
  const Header: typeof import('./components/Header.tsx').Header;
  const LaunchPanel: typeof import('./components/LaunchPanel.tsx').LaunchPanel;
  const ProjectCard: typeof import('./components/ProjectCard.tsx').ProjectCard;
  const ProjectsPanel: typeof import('./components/ProjectsPanel.tsx').ProjectsPanel;
  const QualityPanel: typeof import('./components/QualityPanel.tsx').QualityPanel;
  const RunRow: typeof import('./components/RunRow.tsx').RunRow;
  const RunsPanel: typeof import('./components/RunsPanel.tsx').RunsPanel;
  const Tabs: typeof import('./components/Tabs.tsx').Tabs;
  const Turn: typeof import('./components/Turn.tsx').Turn;
  const WikiPanel: typeof import('./components/WikiPanel.tsx').WikiPanel;
}
export {};
