// GENERATED by scripts/build-ui.mjs — typed globals for the component
// convention (tags resolve by filename; imports are injected at build time).
declare global {
  const h: typeof import('../runtime.ts').h;
  const Fragment: typeof import('../runtime.ts').Fragment;
  const ChecksPanel: typeof import('./components/panels/ChecksPanel.tsx').ChecksPanel;
  const ConsolePanel: typeof import('./components/panels/ConsolePanel.tsx').ConsolePanel;
  const CostPanel: typeof import('./components/panels/CostPanel.tsx').CostPanel;
  const Drawer: typeof import('./components/chrome/Drawer.tsx').Drawer;
  const Gauge: typeof import('./components/viz/Gauge.tsx').Gauge;
  const Header: typeof import('./components/chrome/Header.tsx').Header;
  const LaunchPanel: typeof import('./components/panels/LaunchPanel.tsx').LaunchPanel;
  const NodeGraph: typeof import('./components/viz/NodeGraph.tsx').NodeGraph;
  const ProjectCard: typeof import('./components/items/ProjectCard.tsx').ProjectCard;
  const ProjectsPanel: typeof import('./components/panels/ProjectsPanel.tsx').ProjectsPanel;
  const QualityPanel: typeof import('./components/panels/QualityPanel.tsx').QualityPanel;
  const RunRow: typeof import('./components/items/RunRow.tsx').RunRow;
  const RunsPanel: typeof import('./components/panels/RunsPanel.tsx').RunsPanel;
  const ScanFrame: typeof import('./components/chrome/ScanFrame.tsx').ScanFrame;
  const Spark: typeof import('./components/viz/Spark.tsx').Spark;
  const Tabs: typeof import('./components/chrome/Tabs.tsx').Tabs;
  const TerminalPanel: typeof import('./components/panels/TerminalPanel.tsx').TerminalPanel;
  const Turn: typeof import('./components/items/Turn.tsx').Turn;
  const WikiPanel: typeof import('./components/panels/WikiPanel.tsx').WikiPanel;
}
export {};
