import { mkdir, writeFile, readFile, access } from 'node:fs/promises';
import { join } from 'node:path';
import type { HandlerSpec } from './synth.js';

const SETUP_MARK = 'probevane:msw-global';

// Persist the synthesized mocks the model will use: an MSW handlers module +
// raw fixtures. Generated once by `probevane mock`; the test files import them.

/** Build the MSW handler source lines + the fixture imports they reference.
 *  If a handler's array sample was materialized as a shared fixture, import it
 *  so the SAME frozen data flows through every consumer (the chain contract). */
function buildHandlers(
  handlers: HandlerSpec[],
  fixtures: Record<string, unknown>,
): { imports: Set<string>; handlerLines: string[] } {
  const byName = (sample: unknown): string | null => {
    for (const [name, val] of Object.entries(fixtures))
      if (JSON.stringify(val) === JSON.stringify(sample)) return name;
    return null;
  };
  const imports = new Set<string>();
  const handlerLines = handlers.map((h) => {
    const fname = Array.isArray(h.sample) ? byName(h.sample) : null;
    if (fname) {
      imports.add(`import ${fname} from '../../test-fixtures/${fname}.json';`);
      return `  http.${h.method.toLowerCase()}('${h.urlPattern}', () => HttpResponse.json(${fname})),`;
    }
    const body = JSON.stringify(h.sample, null, 2).replace(/\n/g, '\n  ');
    return `  http.${h.method.toLowerCase()}('${h.urlPattern}', () => HttpResponse.json(${body})),`;
  });
  return { imports, handlerLines };
}

/** Node setup: a server other tests can import + start. */
async function writeServer(mocksDir: string): Promise<void> {
  const serverTs = [
    '// Generated by probevane. MSW node server for vitest. Import + lifecycle in your spec,',
    '// or wire into vitest.setup.ts.',
    "import { setupServer } from 'msw/node';",
    "import { handlers } from './handlers';",
    '',
    'export const server = setupServer(...handlers);',
    '',
  ].join('\n');
  await writeFile(join(mocksDir, 'server.ts'), serverTs);
}

/** Write src/mocks/handlers.ts (+ server.ts) from the deduped handler specs and
 *  wire MSW into vitest.setup.ts so every unit test is hermetic by default. */
export async function writeMocks(
  dir: string,
  handlers: HandlerSpec[],
  fixtures: Record<string, unknown> = {},
): Promise<string> {
  const mocksDir = join(dir, 'src', 'mocks');
  await mkdir(mocksDir, { recursive: true });

  const { imports, handlerLines } = buildHandlers(handlers, fixtures);

  const lines = [
    '// Generated by probevane. MSW request handlers. Array responses import the',
    '// shared test-fixtures/*.json so the same data flows through the whole chain.',
    "import { http, HttpResponse } from 'msw';",
    ...imports,
    '',
    'export const handlers = [',
    ...handlerLines,
    '];',
    '',
  ];
  const handlersPath = join(mocksDir, 'handlers.ts');
  await writeFile(handlersPath, lines.join('\n'));

  await writeServer(mocksDir);

  // Start the MSW server GLOBALLY in vitest.setup.ts so EVERY unit test is
  // hermetic by default — individual specs don't need server lifecycle, only
  // async waiting (findBy/waitFor) and optional per-test `server.use(...)`.
  await patchVitestSetup(dir);

  return handlersPath;
}

/** Idempotently patch vitest.setup.ts: always register jest-dom matchers, and
 *  append the global MSW server block once (guarded by SETUP_MARK). */
async function patchVitestSetup(dir: string): Promise<void> {
  const setupPath = join(dir, 'vitest.setup.ts');
  let existing = (await access(setupPath).then(() => true).catch(() => false))
    ? await readFile(setupPath, 'utf8')
    : '';

  // Always ensure the jest-dom matchers are registered (toBeInTheDocument, etc).
  // The MSW block must never clobber this — it's what makes component tests work.
  const JESTDOM = "import '@testing-library/jest-dom/vitest';";
  if (!existing.includes('@testing-library/jest-dom')) existing = `${JESTDOM}\n${existing}`;

  if (existing.includes(SETUP_MARK)) {
    await writeFile(setupPath, existing); // persist a jest-dom fix even if MSW already present
    return;
  }
  const block = [
    `// ${SETUP_MARK} — MSW server for all tests (generated by probevane)`,
    "import { beforeAll, afterEach, afterAll } from 'vitest';",
    "import { server } from './src/mocks/server';",
    "beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));",
    'afterEach(() => server.resetHandlers());',
    'afterAll(() => server.close());',
    '',
  ].join('\n');
  await writeFile(setupPath, `${existing}\n${block}`);
}
