import { describe, it, expect, afterEach, beforeEach, vi, type Mock } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, mkdirSync, realpathSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

// sh is the only shared spawn boundary used by the modules under test
// (vitest-runner + diff-review.getDiff). Mock it so we can feed canned output
// and assert the pure parse/format branches without spawning anything. git.ts
// uses node:child_process.execFile directly (NOT sh), so a real temp repo is
// unaffected by this mock.
vi.mock('../src/util/exec.js', () => ({
  sh: vi.fn(),
  capOutput: (s: string) => s,
}));

import { sh } from '../src/util/exec.js';
import { buildSpec, type SpecOptions } from '../src/commands/spec/build.js';
import type { StackAdapter, ProbeResult, AdapterCommands } from '../src/adapters/adapter.js';
import { brainFor } from '../src/brain/select.js';
import { runVitest, runPlaywright, mergeResults, coverageVitest } from '../src/adapters/vitest-runner.js';
import { loadConfig, validateConfig, pick } from '../src/util/config.js';
import * as git from '../src/util/git.js';
import {
  parseFindings,
  findingsMarkdown,
  findingsTask,
  getDiff,
  reviewDiffText,
  reviewDiff,
  type Finding,
} from '../src/review/diff-review.js';
import type { Brain } from '../src/brain/brain.js';

const shMock = sh as unknown as Mock;

// --- temp-dir bookkeeping ---------------------------------------------------
const tmps: string[] = [];
function mkTmp(): string {
  const d = mkdtempSync(join(tmpdir(), 'pv-cov-'));
  tmps.push(d);
  return d;
}
afterEach(() => {
  for (const d of tmps.splice(0)) rmSync(d, { recursive: true, force: true });
  vi.clearAllMocks();
});

// ============================================================================
// src/spec/build.ts
// ============================================================================
const CMDS: AdapterCommands = { typecheck: 'tc', lint: 'l', testUnit: 'tu', testE2e: 'te', coverage: 'cov' };

function fakeAdapter(over: Partial<StackAdapter> = {}): StackAdapter {
  return {
    id: 'fake-stack',
    coverage: async () => ({ statements: 88, branches: 70, functions: 90, lines: 88, ok: true }),
    probe: async (_dir: string, target): Promise<ProbeResult> => ({
      target,
      facts: {},
      digest: `Module ${target.sourcePath}\n- exports: foo, bar\n- note: stuff`,
      ok: true,
    }),
    commands: () => CMDS,
    ...over,
  } as unknown as StackAdapter;
}

/** A tiny project with three modules that import each other + one fetcher. */
function makeProject(): string {
  const dir = mkTmp();
  const src = join(dir, 'src');
  mkdirSync(src, { recursive: true });
  writeFileSync(join(src, 'util.ts'), `export const TAX = 0.2;\nexport function calc(n: number) { return n * TAX; }\n`);
  writeFileSync(
    join(src, 'api.ts'),
    `import { calc } from './util.js';\nconst BASE = '/api';\nexport async function getProducts() { const r = await fetch(\`\${BASE}/products\`); return r.json(); }\nexport function priced(n: number) { return calc(n); }\n`,
  );
  writeFileSync(
    join(src, 'widget.tsx'),
    `import { getProducts } from './api.js';\nexport default function Widget() { void getProducts; return null; }\n`,
  );
  return dir;
}

describe('spec/build buildSpec', () => {
  it('assembles the full markdown spec (overview/graph/modules/api) without a brain', async () => {
    const dir = makeProject();
    const opts: SpecOptions = { dir, adapter: fakeAdapter(), stamp: '2026-01-01' };
    const md = await buildSpec(opts);

    // header + stamp
    expect(md).toContain('— Specification');
    expect(md).toContain('Generated by probevane (fake-stack) on 2026-01-01');
    // overviewLines: graph summary + endpoint count + coverage
    expect(md).toContain('## Overview');
    expect(md).toContain('3 modules');
    expect(md).toContain('network endpoint(s)');
    expect(md).toContain('test coverage: 88% statements, 70% branches');
    // graphLines: ascii + mermaid
    expect(md).toContain('## Module graph');
    expect(md).toContain('```mermaid');
    // modulesLines + moduleSection: per-module header, net emoji, probe facts
    expect(md).toContain('## Modules');
    expect(md).toContain('### src/api.ts');
    expect(md).toContain('🌐'); // api is a fetcher (callsNetwork)
    expect(md).toContain('- exports: foo, bar'); // probe digest facts injected
    expect(md).toContain('depends on:'); // api/widget have local deps
    // apiLines (non-empty): API surface from the synthesized handler
    expect(md).toContain('## API surface');
    expect(md).toContain('GET /api/products');
  });

  it('covers the empty/catch branches: coverage() rejects, probe ok:false, no stamp', async () => {
    const dir = makeProject();
    const adapter = fakeAdapter({
      coverage: async () => {
        throw new Error('no coverage');
      },
      probe: async (_dir: string, target): Promise<ProbeResult> => ({
        target,
        facts: {},
        digest: '',
        ok: false,
        error: 'probe failed',
      }),
    });
    const md = await buildSpec({ dir, adapter });

    expect(md).toContain('## Overview');
    expect(md).not.toContain('test coverage:'); // cov null → no coverage line
    expect(md).not.toContain(' on '); // no stamp → no " on <stamp>"
    expect(md).toContain('## Modules'); // still renders module sections
    expect(md).not.toContain('- exports:'); // probe ok:false → no facts injected
  });
});

// ============================================================================
// src/brain/select.ts
// ============================================================================
describe('brain/select brainFor', () => {
  const saved = process.env.PROBEVANE_RECORD;
  beforeEach(() => {
    delete process.env.PROBEVANE_RECORD;
  });
  afterEach(() => {
    if (saved === undefined) delete process.env.PROBEVANE_RECORD;
    else process.env.PROBEVANE_RECORD = saved;
  });

  it('undefined / auto → anthropic brain', () => {
    expect(brainFor().id).toBe('anthropic-sdk');
    expect(brainFor('auto').id).toBe('anthropic-sdk');
  });

  it('haiku/sonnet/opus resolve their aliased model ids', () => {
    expect(brainFor('haiku')).toMatchObject({ id: 'anthropic-sdk', model: 'claude-haiku-4-5-20251001' });
    expect(brainFor('sonnet').model).toBe('claude-sonnet-4-6');
    expect(brainFor('opus').model).toBe('claude-opus-4-8');
  });

  it('an unknown model id passes through as-is (alias fallback)', () => {
    expect(brainFor('claude-custom-9')).toMatchObject({ id: 'anthropic-sdk', model: 'claude-custom-9' });
  });

  it('bridge / claude-code / cc:<m> branches', () => {
    expect(brainFor('bridge')).toMatchObject({ id: 'bridge', model: 'bridge' });
    expect(brainFor('claude-code')).toMatchObject({ id: 'claude-code', model: 'claude-code' });
    expect(brainFor('cc:gpt')).toMatchObject({ id: 'claude-code', model: 'claude-code:gpt' });
  });

  it('local:<id> / openai:<id> → openai-compat brain', () => {
    expect(brainFor('local:qwen')).toMatchObject({ id: 'openai-compat', model: 'qwen' });
    expect(brainFor('openai:gpt-4o')).toMatchObject({ id: 'openai-compat', model: 'gpt-4o' });
  });

  it('replay:<file> → replay brain (and bypasses PROBEVANE_RECORD wrapping)', () => {
    expect(brainFor('replay:/tmp/cassette.jsonl').id).toBe('replay');
    process.env.PROBEVANE_RECORD = join(mkTmp(), 'rec.jsonl');
    expect(brainFor('replay:/tmp/cassette.jsonl').id).toBe('replay'); // returns before rec check
  });

  it('PROBEVANE_RECORD wraps a live brain in a recording brain', () => {
    process.env.PROBEVANE_RECORD = join(mkTmp(), 'rec.jsonl');
    expect(brainFor('local:qwen').id).toBe('record(openai-compat)');
    expect(brainFor('opus').id).toBe('record(anthropic-sdk)');
  });
});

// ============================================================================
// src/adapters/vitest-runner.ts
// ============================================================================
describe('adapters/vitest-runner', () => {
  it('runVitest parses a green json report', async () => {
    const dir = mkTmp();
    writeFileSync(
      join(dir, '.probevane-vitest.json'),
      JSON.stringify({ numPassedTests: 5, numFailedTests: 0, numPendingTests: 1, numTodoTests: 0 }),
    );
    shMock.mockResolvedValue({ code: 0, stdout: 'out', stderr: '', ok: true });
    const r = await runVitest(dir);
    expect(r).toMatchObject({ passed: 5, failed: 0, skipped: 1, green: true });
  });

  it('runVitest: passing tests but failures present → not green', async () => {
    const dir = mkTmp();
    writeFileSync(join(dir, '.probevane-vitest.json'), JSON.stringify({ numPassedTests: 3, numFailedTests: 2 }));
    shMock.mockResolvedValue({ code: 1, stdout: '', stderr: 'boom', ok: false });
    const r = await runVitest(dir);
    expect(r).toMatchObject({ passed: 3, failed: 2, green: false });
  });

  it('runVitest: missing/unparsable report → catch branch, failed forced to >=1 when run failed', async () => {
    const dir = mkTmp(); // no report file written
    shMock.mockResolvedValue({ code: 1, stdout: '', stderr: 'crash', ok: false });
    const r = await runVitest(dir);
    expect(r.passed).toBe(0);
    expect(r.failed).toBeGreaterThanOrEqual(1);
    expect(r.green).toBe(false);
  });

  it('runVitest passes scoped files through to sh', async () => {
    const dir = mkTmp();
    writeFileSync(join(dir, '.probevane-vitest.json'), JSON.stringify({ numPassedTests: 1, numFailedTests: 0 }));
    shMock.mockResolvedValue({ code: 0, stdout: '', stderr: '', ok: true });
    await runVitest(dir, ['a.test.ts', 'b.test.ts']);
    const cmd = shMock.mock.calls[0][0] as string;
    expect(cmd).toContain('"a.test.ts"');
    expect(cmd).toContain('"b.test.ts"');
  });

  it('runPlaywright: green line-reporter output', async () => {
    shMock.mockResolvedValue({ code: 0, stdout: '3 passed (1.2s)', stderr: '', ok: true });
    const r = await runPlaywright(mkTmp());
    expect(r).toMatchObject({ passed: 3, failed: 0, green: true });
  });

  it('runPlaywright: failures + skips parsed, not green', async () => {
    shMock.mockResolvedValue({ code: 1, stdout: '1 passed\n2 failed\n1 skipped', stderr: '', ok: false });
    const r = await runPlaywright(mkTmp(), ['x.e2e.ts']);
    expect(r).toMatchObject({ passed: 1, failed: 2, skipped: 1, green: false });
  });

  it('runPlaywright: no tests at all → total 0, not green', async () => {
    shMock.mockResolvedValue({ code: 0, stdout: 'no tests found', stderr: '', ok: true });
    const r = await runPlaywright(mkTmp());
    expect(r).toMatchObject({ passed: 0, failed: 0, green: false });
  });

  it('mergeResults: single part returned unchanged', () => {
    const one = { passed: 2, failed: 0, skipped: 0, green: true, raw: 'x' };
    expect(mergeResults([one])).toBe(one);
  });

  it('mergeResults: aggregates counts and ANDs green', () => {
    const merged = mergeResults([
      { passed: 2, failed: 0, skipped: 1, green: true, raw: 'a' },
      { passed: 3, failed: 1, skipped: 0, green: false, raw: 'b' },
    ]);
    expect(merged).toMatchObject({ passed: 5, failed: 1, skipped: 1, green: false });
    expect(merged.raw).toContain('a');
    expect(merged.raw).toContain('b');
  });

  it('coverageVitest: parses coverage-summary.json when present', async () => {
    const dir = mkTmp();
    mkdirSync(join(dir, 'coverage'), { recursive: true });
    writeFileSync(
      join(dir, 'coverage', 'coverage-summary.json'),
      JSON.stringify({ total: { statements: { pct: 91 }, branches: { pct: 80 }, functions: { pct: 85 }, lines: { pct: 91 } } }),
    );
    shMock.mockResolvedValue({ code: 0, stdout: 'cov-stdout', stderr: '', ok: true });
    const c = await coverageVitest(dir);
    expect(c).toMatchObject({ statements: 91, branches: 80, functions: 85, lines: 91, ok: true });
    expect(c.raw).toContain('cov-stdout');
  });

  it('coverageVitest: missing summary → ok:false, raw from stdout+stderr', async () => {
    const dir = mkTmp(); // no coverage dir
    shMock.mockResolvedValue({ code: 1, stdout: 'so', stderr: 'se', ok: false });
    const c = await coverageVitest(dir);
    expect(c.ok).toBe(false);
    expect(c.statements).toBe(0);
    expect(c.raw).toContain('se');
  });
});

// ============================================================================
// src/config.ts
// ============================================================================
describe('config loadConfig / validateConfig / pick', () => {
  it('absent config → defaults to {}', async () => {
    expect(await loadConfig(mkTmp())).toEqual({});
  });

  it('valid probevane.config.json is parsed and merged', async () => {
    const dir = mkTmp();
    writeFileSync(join(dir, 'probevane.config.json'), JSON.stringify({ model: 'haiku', minTests: 3, mock: true }));
    expect(await loadConfig(dir)).toEqual({ model: 'haiku', minTests: 3, mock: true });
  });

  it('config with validation issues still loads but logs them', async () => {
    const dir = mkTmp();
    writeFileSync(join(dir, 'probevane.config.json'), JSON.stringify({ bogus: 1 }));
    const spy = vi.spyOn(console, 'error').mockImplementation(() => {});
    const cfg = await loadConfig(dir);
    expect(cfg).toEqual({ bogus: 1 });
    expect(spy).toHaveBeenCalled();
    spy.mockRestore();
  });

  it('invalid JSON → throws the load error (catch path)', async () => {
    const dir = mkTmp();
    writeFileSync(join(dir, 'probevane.config.json'), '{ this is not json ');
    await expect(loadConfig(dir)).rejects.toThrow(/failed to load probevane\.config\.json/);
  });

  it('validateConfig flags non-objects, unknown keys, wrong types, bad kind', () => {
    expect(validateConfig(null)).toEqual(['config must be an object']);
    expect(validateConfig('nope')).toEqual(['config must be an object']);
    expect(validateConfig({ maxStep: 1 })).toEqual(['unknown key "maxStep"']);
    expect(validateConfig({ minTests: '5' })).toEqual(['"minTests" must be number (got string)']);
    expect(validateConfig({ kind: 'wat' })).toEqual(['"kind" must be "unit" or "e2e"']);
    expect(validateConfig({ model: 'x', kind: 'unit', minTests: 2, mock: true })).toEqual([]);
  });

  it('validateConfig accepts the nested arch role block, rejects malformed ones', () => {
    expect(validateConfig({ arch: { glue: ['cli'], shared: ['util', 'cost'] } })).toEqual([]);
    expect(validateConfig({ arch: { glue: [] } })).toEqual([]);
    expect(validateConfig({ arch: 'cli' })).toEqual(['"arch" must be an object ({ glue?, shared? })']);
    expect(validateConfig({ arch: ['cli'] })).toEqual(['"arch" must be an object ({ glue?, shared? })']);
    expect(validateConfig({ arch: { blue: ['cli'] } })).toEqual(['unknown key "arch.blue"']);
    expect(validateConfig({ arch: { glue: 'cli' } })).toEqual(['"arch.glue" must be string[]']);
    expect(validateConfig({ arch: { shared: ['util', 7] } })).toEqual(['"arch.shared" must be string[]']);
  });

  it('pick returns the first defined value, else undefined', () => {
    expect(pick(undefined, 2, 3)).toBe(2);
    expect(pick('a')).toBe('a');
    expect(pick<number>(undefined, undefined)).toBeUndefined();
  });
});

// ============================================================================
// src/util/git.ts (real temp repo)
// ============================================================================
function gitCmd(dir: string, ...args: string[]): string {
  return execFileSync('git', args, { cwd: dir, stdio: ['ignore', 'pipe', 'ignore'] }).toString();
}
function makeRepo(): string {
  const dir = mkTmp();
  gitCmd(dir, 'init', '-b', 'main');
  gitCmd(dir, 'config', 'user.email', 'tester@example.com');
  gitCmd(dir, 'config', 'user.name', 'Tester');
  writeFileSync(join(dir, 'a.txt'), 'hello\n');
  gitCmd(dir, 'add', 'a.txt');
  gitCmd(dir, 'commit', '-m', 'init');
  return dir;
}

describe('util/git in a real temp repo', () => {
  it('isGitRepo / repoRoot / headSha / currentBranch (repo + non-repo)', async () => {
    const repo = makeRepo();
    const bare = mkTmp();

    expect(await git.isGitRepo(repo)).toBe(true);
    expect(await git.isGitRepo(bare)).toBe(false);

    expect(await git.repoRoot(repo)).toBe(realpathSync(repo));
    expect(await git.repoRoot(bare)).toBe('');

    expect(await git.headSha(repo)).toMatch(/^[0-9a-f]{40}$/);
    expect(await git.headSha(bare)).toBe('');

    expect(await git.currentBranch(repo)).toBe('main');
    expect(await git.currentBranch(bare)).toBe('');
  });

  it('diffStat reflects working-tree edits; clean tree is empty', async () => {
    const repo = makeRepo();
    expect(await git.diffStat(repo)).toBe('');
    expect(await git.diffStat(repo, 'HEAD')).toBe(''); // base-arg branch
    writeFileSync(join(repo, 'a.txt'), 'hello\nworld\n');
    expect(await git.diffStat(repo)).toContain('a.txt');
  });

  it('fileExistedAt / showFile resolve content at a sha; absent → false / empty', async () => {
    const repo = makeRepo();
    const sha = await git.headSha(repo);
    expect(await git.fileExistedAt(repo, sha, 'a.txt')).toBe(true);
    expect(await git.fileExistedAt(repo, sha, 'ghost.txt')).toBe(false);
    expect(await git.showFile(repo, sha, 'a.txt')).toBe('hello\n');
    expect(await git.showFile(repo, sha, 'ghost.txt')).toBe('');
    expect(await git.showFile(repo, '', 'a.txt')).toBe(''); // empty sha → early ''
    expect(await git.headSha(bareDir())).toBe('');
  });
  function bareDir() {
    return mkTmp();
  }

  it('restoreFile rolls a file back to its committed content', async () => {
    const repo = makeRepo();
    const sha = await git.headSha(repo);
    writeFileSync(join(repo, 'a.txt'), 'corrupted\n');
    expect(await git.restoreFile(repo, sha, 'a.txt')).toBe(true);
    expect(readFileSync(join(repo, 'a.txt'), 'utf8')).toBe('hello\n');
  });

  it('createBranch switches branch; commitFiles needs files and commits them', async () => {
    const repo = makeRepo();
    expect(await git.commitFiles(repo, [], 'noop')).toBe(false); // empty file list
    writeFileSync(join(repo, 'b.txt'), 'second\n');
    expect(await git.commitFiles(repo, ['b.txt'], 'add b')).toBe(true);

    expect(await git.createBranch(repo, 'feature')).toBe(true);
    expect(await git.currentBranch(repo)).toBe('feature');
  });

  it('hasRemote is false without an origin', async () => {
    expect(await git.hasRemote(makeRepo())).toBe(false);
  });

  it('addWorktree + removeWorktree are safe in a temp repo', async () => {
    const repo = makeRepo();
    const wt = join(mkTmp(), 'wt');
    expect(await git.addWorktree(repo, wt, 'wt-branch')).toBe(true);
    expect(existsSync(wt)).toBe(true);
    await git.removeWorktree(repo, wt, 'wt-branch');
    expect(existsSync(wt)).toBe(false);
  });

  it('mergeBranch performs a no-ff merge of a feature commit', async () => {
    const repo = makeRepo();
    await git.createBranch(repo, 'feat');
    writeFileSync(join(repo, 'feat.txt'), 'feature\n');
    await git.commitFiles(repo, ['feat.txt'], 'feat commit');
    gitCmd(repo, 'checkout', 'main');
    expect(await git.mergeBranch(repo, 'feat', 'merge feat')).toBe(true);
    expect(existsSync(join(repo, 'feat.txt'))).toBe(true);
  });

  it('revertEdits restores tracked files and removes run-created ones', async () => {
    const repo = makeRepo();
    const sha = await git.headSha(repo);
    writeFileSync(join(repo, 'a.txt'), 'edited\n'); // existed at sha → restored
    writeFileSync(join(repo, 'new.txt'), 'created\n'); // not at sha → removed
    const res = await git.revertEdits(repo, sha, ['a.txt', 'new.txt']);
    expect(res).toEqual({ restored: 1, removed: 1 });
    expect(readFileSync(join(repo, 'a.txt'), 'utf8')).toBe('hello\n');
    expect(existsSync(join(repo, 'new.txt'))).toBe(false);
  });
});

// ============================================================================
// src/review/diff-review.ts
// ============================================================================
const FINDING: Finding = { file: 'src/a.ts', line: 3, severity: 'error', issue: 'off-by-one', fix: 'use <=' };

function fakeBrain(text: string, throws = false): Brain {
  return {
    id: 'fake',
    model: 'fake',
    async complete() {
      if (throws) throw new Error('brain down');
      return { text, toolCalls: [], stopReason: 'end_turn', usage: { input: 0, output: 0 } };
    },
  };
}

describe('review/diff-review', () => {
  it('parseFindings: valid JSON array → normalized findings', () => {
    const out = parseFindings(JSON.stringify([FINDING]));
    expect(out).toEqual([FINDING]);
  });

  it('parseFindings: fenced ```json block is extracted', () => {
    const out = parseFindings('here you go:\n```json\n' + JSON.stringify([FINDING]) + '\n```\nthanks');
    expect(out).toHaveLength(1);
    expect(out[0].file).toBe('src/a.ts');
  });

  it('parseFindings: garbage → [] and non-array → []', () => {
    expect(parseFindings('no json at all')).toEqual([]);
    expect(parseFindings('{"not":"an array"}')).toEqual([]);
  });

  it('parseFindings: normalizes severity, line, fix and drops incomplete entries', () => {
    const raw = JSON.stringify([
      { file: 'x.ts', issue: 'bad sev', severity: 'critical', line: 'NaN' }, // sev→warn, line→undefined, fix→''
      { file: 'y.ts', issue: 'no fix', severity: 'nit', line: 7 },
      { severity: 'error', issue: 'no file' }, // dropped (no file)
      { file: 'z.ts', severity: 'error' }, // dropped (no issue)
    ]);
    const out = parseFindings(raw);
    expect(out).toEqual([
      { file: 'x.ts', line: undefined, severity: 'warn', issue: 'bad sev', fix: '' },
      { file: 'y.ts', line: 7, severity: 'nit', issue: 'no fix', fix: '' },
    ]);
  });

  it('findingsMarkdown: empty → clean message; non-empty → icons + locations + fixes', () => {
    expect(findingsMarkdown([])).toContain('No issues found');
    const md = findingsMarkdown([
      FINDING,
      { file: 'b.ts', severity: 'nit', issue: 'style', fix: '' },
    ]);
    expect(md).toContain('2 finding(s)');
    expect(md).toContain('🛑');
    expect(md).toContain('`src/a.ts:3`');
    expect(md).toContain('→ use <=');
    expect(md).toContain('💡');
    expect(md).toContain('`b.ts`'); // no line → no :line suffix
  });

  it('findingsTask renders a numbered remediation task', () => {
    const task = findingsTask([FINDING, { file: 'b.ts', severity: 'warn', issue: 'leak', fix: 'close it' }]);
    expect(task).toContain('A code review found');
    expect(task).toContain('1. [error] src/a.ts:3 — off-by-one (suggested: use <=)');
    expect(task).toContain('2. [warn] b.ts — leak (suggested: close it)');
  });

  it('getDiff returns sliced sh stdout; empty stdout → empty string', async () => {
    shMock.mockResolvedValue({ code: 0, stdout: 'diff --git a b\n+added', stderr: '', ok: true });
    expect(await getDiff(mkTmp(), 'HEAD')).toContain('+added');
    shMock.mockResolvedValue({ code: 0, stdout: '', stderr: '', ok: true });
    expect(await getDiff(mkTmp(), 'HEAD')).toBe('');
  });

  it('reviewDiffText: empty diff short-circuits to []', async () => {
    expect(await reviewDiffText('   ', fakeBrain('[]'))).toEqual([]);
  });

  it('reviewDiffText: parses a fake brain reply', async () => {
    const out = await reviewDiffText('some real diff', fakeBrain(JSON.stringify([FINDING])));
    expect(out).toEqual([FINDING]);
  });

  it('reviewDiffText: brain failure → catch → []', async () => {
    expect(await reviewDiffText('some real diff', fakeBrain('', true))).toEqual([]);
  });

  it('reviewDiff: wires getDiff(sh) → reviewDiffText(brain)', async () => {
    shMock.mockResolvedValue({ code: 0, stdout: 'a real diff body', stderr: '', ok: true });
    const out = await reviewDiff(mkTmp(), 'HEAD', fakeBrain(JSON.stringify([FINDING])));
    expect(out).toEqual([FINDING]);
  });
});
