import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { reduceJobs, jobsToEvict, type PersistedJob } from '../src/observe/jobs.js';

const job = (over: Partial<PersistedJob> = {}): PersistedJob => ({
  id: 'a',
  op: 'quality',
  dir: '/x',
  flags: [],
  status: 'done',
  startedAt: '2026-06-27T00:00:00Z',
  tail: [],
  ...over,
});

describe('reduceJobs', () => {
  it('keeps the last write per id', () => {
    const rows = [
      job({ id: 'a', status: 'running' }),
      job({ id: 'a', status: 'done', exitCode: 0 }),
      job({ id: 'b', status: 'error', exitCode: 1 }),
    ];
    const out = reduceJobs(rows);
    expect(out).toHaveLength(2);
    expect(out.find((j) => j.id === 'a')?.status).toBe('done');
  });

  it("marks an orphaned 'running' job as error", () => {
    const out = reduceJobs([job({ id: 'a', status: 'running' })]);
    expect(out[0].status).toBe('error');
    expect(out[0].exitCode).toBe(-1);
  });

  it('leaves finished jobs untouched', () => {
    const out = reduceJobs([job({ id: 'a', status: 'done', exitCode: 0 })]);
    expect(out[0].status).toBe('done');
    expect(out[0].exitCode).toBe(0);
  });
});

describe('jobsToEvict', () => {
  it('returns [] within budget', () => {
    expect(jobsToEvict([job({ id: 'a' }), job({ id: 'b' })], 5)).toEqual([]);
  });

  it('evicts the oldest finished jobs past the cap', () => {
    const jobs = [
      job({ id: 'old', status: 'done', startedAt: '2026-01-01T00:00:00Z' }),
      job({ id: 'mid', status: 'error', startedAt: '2026-02-01T00:00:00Z' }),
      job({ id: 'new', status: 'done', startedAt: '2026-03-01T00:00:00Z' }),
    ];
    expect(jobsToEvict(jobs, 2)).toEqual(['old']);
  });

  it('never evicts a running job even when over cap', () => {
    const jobs = [
      job({ id: 'r1', status: 'running', startedAt: '2026-01-01T00:00:00Z' }),
      job({ id: 'r2', status: 'running', startedAt: '2026-02-01T00:00:00Z' }),
    ];
    expect(jobsToEvict(jobs, 1)).toEqual([]); // nothing finished to drop
  });
});

describe('control center XSS guard (asset)', () => {
  // control.html is GENERATED from src/ui/app/ (scripts/build-ui.mjs); the
  // static invariants now live in the sources — Turn.tsx is the transcript
  // renderer (highest XSS surface: arbitrary model output + file contents),
  // and the h() runtime's default child path is createTextNode. The runtime
  // proof is e2e-dash/control-center.spec.ts's XSS spec.
  const ui = (rel: string) =>
    readFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'ui', rel), 'utf8');
  const html = ui('control.html');

  it('is generated + self-contained, with an esc() escaper in the bundle', () => {
    expect(html).toContain('GENERATED by scripts/build-ui.mjs');
    expect(html).toMatch(/esc = /);
    expect(html).toContain('&lt;');
  });
  it('transcript renderer (Turn.tsx) never touches innerHTML; runtime defaults to text nodes', () => {
    expect(ui('app/components/Turn.tsx')).not.toMatch(/innerHTML/);
    expect(ui('runtime.ts')).toMatch(/createTextNode/);
  });
  it('every innerHTML site in the app escapes interpolations or injects trusted markdown/mermaid only', () => {
    const main = ui('app/main.tsx');
    for (const line of main.split('\n').filter((l) => l.includes('innerHTML') && !l.trim().startsWith('//'))) {
      expect(line, line).toMatch(/esc\(|= html|= svg|'<span class="muted">none<\/span>'/);
    }
  });
  it('renders wiki markdown only with mermaid securityLevel strict', () => {
    expect(html).toMatch(/securityLevel:\s*["\']strict["\']/);
  });
  it('has the control-center tabs (rendered from the theme SSOT)', async () => {
    const { TABS } = await import('../src/util/theme.js');
    const ids = TABS.map((t) => t.id);
    for (const t of ['projects', 'runs', 'docs', 'launch', 'cost', 'quality', 'console', 'terminal']) expect(ids).toContain(t);
    expect(ui('app/components/Tabs.tsx')).toContain('TABS'); // Tabs renders from the model, not literal markup
  });
});
