import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, basename } from 'node:path';
import { buildSpec } from '../src/commands/spec/build.js';
import type { StackAdapter, TestTarget } from '../src/adapters/adapter.js';
import type { Brain } from '../src/brain/brain.js';

// buildSpec's deterministic path only (no brain → no --narrate): a tiny two-module
// project — a pure util plus a fetcher importing it — must yield every SPEC section
// with the graph, coverage, probe facts, and API surface distilled in.

/** Only the two methods buildSpec touches: coverage + per-module probe. */
const adapter = {
  id: 'fake-stack',
  async coverage() { return { statements: 77, branches: 61, functions: 50, lines: 77, ok: true }; },
  async probe(_dir: string, target: TestTarget) {
    return {
      target,
      facts: {},
      digest: `PROBE ${target.sourcePath}\n- exports: ${target.name}\nnot a fact line`,
      ok: true,
    };
  },
} as unknown as StackAdapter;

let dir: string;
let spec: string;

beforeAll(async () => {
  dir = mkdtempSync(join(tmpdir(), 'pv-spec-'));
  mkdirSync(join(dir, 'src'), { recursive: true });
  writeFileSync(join(dir, 'src', 'util.ts'), 'export function add(a: number, b: number): number { return a + b; }\n');
  writeFileSync(
    join(dir, 'src', 'api.ts'),
    "import { add } from './util.js';\n" +
      "export async function fetchItems() {\n  const r = await fetch('/api/items');\n  return add(1, 2) + (await r.json()).length;\n}\n",
  );
  spec = await buildSpec({ dir, adapter, stamp: '2026-01-01' });
});
afterAll(() => dir && rmSync(dir, { recursive: true, force: true }));

describe('spec.buildSpec (deterministic, no narration)', () => {
  it('titles the SPEC with the project name, adapter id, and stamp', () => {
    expect(spec).toContain(`# ${basename(dir)} — Specification`);
    expect(spec).toContain('_Generated by probevane (fake-stack) on 2026-01-01._');
  });

  it('emits every section header in order', () => {
    const idx = ['## Overview', '## Module graph', '## Modules', '## API surface'].map((h) => spec.indexOf(h));
    expect(idx.every((i) => i >= 0)).toBe(true);
    expect([...idx].sort((a, b) => a - b)).toEqual(idx);
  });

  it('overview distils the graph summary, endpoint count, and coverage', () => {
    expect(spec).toContain('2 modules');
    expect(spec).toContain('1 touch the network');
    expect(spec).toContain('- 1 network endpoint(s)');
    expect(spec).toContain('- test coverage: 77% statements, 61% branches');
  });

  it('module graph renders both an ascii tree and a mermaid block', () => {
    expect(spec).toContain('```mermaid');
    expect(spec).toContain('util.ts'); // both views strip the src/ prefix
    expect(spec).toContain('api.ts');
  });

  it('lists modules leaf-first with kind, dependency, and probe fact lines', () => {
    expect(spec).toContain('### src/util.ts — util');
    expect(spec).toContain('### src/api.ts — fetcher 🌐');
    expect(spec.indexOf('### src/util.ts')).toBeLessThan(spec.indexOf('### src/api.ts')); // deps first
    expect(spec).toContain('- depends on: src/util.ts');
    expect(spec).toContain('  - exports: util'); // probe digest fact, indented
    expect(spec).toContain('  - exports: api');
    expect(spec).not.toContain('not a fact line'); // non-"-" digest lines are dropped
  });

  it('API surface lists the fetch call as a handler', () => {
    expect(spec).toContain('- `GET /api/items`');
  });

  it('omits the oracles section when none are declared', () => {
    expect(spec).not.toContain('## Acceptance oracles');
  });

  it('renders declared oracles from probevane.config as a table', async () => {
    const d = mkdtempSync(join(tmpdir(), 'pv-spec-ora-'));
    mkdirSync(join(d, 'src'), { recursive: true });
    writeFileSync(join(d, 'src', 'rng.ts'), 'export const next = (s: number) => s + 1;\n');
    writeFileSync(join(d, 'probevane.config.json'), JSON.stringify({
      oracles: { 'src/rng.ts': { kind: 'byte-stable', desc: 'seed → identical stream', blocking: true } },
    }));
    const s = await buildSpec({ dir: d, adapter, stamp: '2026-01-01' });
    expect(s).toContain('## Acceptance oracles');
    expect(s).toContain('| src/rng.ts | byte-stable | seed → identical stream | yes |');
    rmSync(d, { recursive: true, force: true });
  });

  it('a brain narrates modules as `path: sentence` lines woven into their sections', async () => {
    // Deterministic in-memory brain — no model, no network. Replies one line per
    // module plus noise lines that parseNarratives must ignore.
    const brain: Brain = {
      id: 'fake',
      model: 'fake',
      async complete() {
        return {
          text: 'preamble to ignore\nsrc/util.ts: Adds two numbers.\nsrc/api.ts: Fetches items.\nsrc/ghost.ts: Not a module.',
          toolCalls: [],
          stopReason: 'end_turn',
          usage: { input: 0, output: 0 },
        };
      },
    };
    const narrated = await buildSpec({ dir, adapter, brain });
    expect(narrated).toContain('Adds two numbers.');
    expect(narrated).toContain('Fetches items.');
    expect(narrated).not.toContain('Not a module.'); // unknown path dropped
    expect(narrated).not.toContain('preamble to ignore');
    // the narrative lands inside the module's section
    const utilAt = narrated.indexOf('### src/util.ts');
    const apiAt = narrated.indexOf('### src/api.ts');
    const sentenceAt = narrated.indexOf('Adds two numbers.');
    expect(sentenceAt).toBeGreaterThan(utilAt);
    expect(sentenceAt).toBeLessThan(apiAt);
  });

  it('a failing brain degrades to the unnarrated SPEC (no throw)', async () => {
    const broken: Brain = {
      id: 'broken',
      model: 'broken',
      async complete() { throw new Error('model down'); },
    };
    const bare = await buildSpec({ dir, adapter, brain: broken });
    expect(bare).toContain('### src/util.ts — util');
    expect(bare).toContain('## API surface');
  });

  it('coverage failure just drops the coverage bullet (no throw)', async () => {
    const noCov = {
      ...(adapter as object),
      async coverage() { throw new Error('nope'); },
    } as unknown as StackAdapter;
    const bare = await buildSpec({ dir, adapter: noCov });
    expect(bare).toContain('# ');
    expect(bare).not.toContain('test coverage:');
    expect(bare).not.toContain(' on 2026'); // no stamp → no " on"
  });
});
