import { basename } from 'node:path';
import type { StackAdapter } from '../adapters/adapter.js';
import type { Brain } from '../brain/brain.js';
import { buildGraph } from '../mock/graph.js';
import { buildMockPlan } from '../mock/index.js';
import { toMermaid, toAscii, graphSummary } from '../mock/render.js';

// Project specification generator. Distils the structure probevane already
// discovers — the module graph, each module's exports/probe facts, the network
// surface, and test coverage — into a human-readable SPEC.md. Deterministic by
// default; `--narrate` adds a one-line LLM description per module.

export interface SpecOptions {
  dir: string;
  adapter: StackAdapter;
  brain?: Brain; // when set, narrate each module
  stamp?: string; // caller-provided timestamp (scripts can't use Date.now)
}

export async function buildSpec(opts: SpecOptions): Promise<string> {
  const { dir, adapter } = opts;
  const graph = await buildGraph(dir);
  const plan = await buildMockPlan(dir).catch(() => null);
  const cov = await adapter.coverage(dir).catch(() => null);
  const name = basename(dir);

  const narratives = opts.brain ? await narrate(opts.brain, graph, adapter, dir) : {};

  const lines: string[] = [];
  lines.push(`# ${name} — Specification`);
  lines.push('');
  lines.push(`_Generated by probevane (${adapter.id})${opts.stamp ? ` on ${opts.stamp}` : ''}._`);
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(`- ${graphSummary(graph)}`);
  if (plan?.handlers.length) lines.push(`- ${plan.handlers.length} network endpoint(s)`);
  if (cov?.ok) lines.push(`- test coverage: ${cov.statements}% statements, ${cov.branches}% branches`);
  lines.push('');

  // Graph
  lines.push('## Module graph');
  lines.push('');
  lines.push('```');
  lines.push(toAscii(graph));
  lines.push('```');
  lines.push('');
  lines.push(toMermaid(graph));
  lines.push('');

  // Modules (leaf-first, the build/chain order)
  lines.push('## Modules');
  lines.push('');
  for (const path of graph.order) {
    const n = graph.nodes.get(path)!;
    lines.push(`### ${path} — ${n.kind}${n.callsNetwork ? ' 🌐' : ''}`);
    if (narratives[path]) lines.push('', narratives[path]);
    const deps = n.imports.filter((d) => graph.nodes.has(d));
    if (deps.length) lines.push('', `- depends on: ${deps.join(', ')}`);
    const probe = await adapter.probe(dir, { kind: 'unit', sourcePath: path, name: path.split('/').pop()!.replace(/\.\w+$/, '') });
    if (probe.ok && probe.digest) {
      const facts = probe.digest.split('\n').slice(1).filter((l) => l.trim().startsWith('-'));
      if (facts.length) lines.push('', ...facts.map((f) => `  ${f.trim()}`));
    }
    lines.push('');
  }

  // API surface
  if (plan?.handlers.length) {
    lines.push('## API surface');
    lines.push('');
    for (const h of plan.handlers) lines.push(`- \`${h.method} ${h.urlPattern}\``);
    lines.push('');
  }

  return lines.join('\n');
}

async function narrate(
  brain: Brain,
  graph: Awaited<ReturnType<typeof buildGraph>>,
  adapter: StackAdapter,
  dir: string,
): Promise<Record<string, string>> {
  // Gather each module's probe digest, ask for a one-line description each.
  const digests: string[] = [];
  for (const path of graph.order) {
    const probe = await adapter.probe(dir, { kind: 'unit', sourcePath: path, name: path });
    digests.push(`${path} (${graph.nodes.get(path)!.kind}):\n${probe.digest}`);
  }
  const sys = 'You document codebases. For each module below, write ONE concise sentence describing its responsibility. Reply as lines `path: sentence`, nothing else.';
  const resp = await brain
    .complete({ system: sys, messages: [{ role: 'user', text: digests.join('\n\n') }], tools: [] })
    .catch(() => null);
  const out: Record<string, string> = {};
  for (const line of (resp?.text ?? '').split('\n')) {
    const m = line.match(/^\s*([^\s:]+):\s*(.+)$/);
    if (m && graph.nodes.has(m[1])) out[m[1]] = m[2].trim();
  }
  return out;
}
