import { basename } from 'node:path';
import type { StackAdapter } from '../adapters/adapter.js';
import type { Brain } from '../brain/brain.js';
import { buildGraph } from '../mock/graph.js';
import { buildMockPlan } from '../mock/index.js';
import { toMermaid, toAscii, graphSummary } from '../mock/render.js';

// Project specification generator. Distils the structure probevane already
// discovers — the module graph, each module's exports/probe facts, the network
// surface, and test coverage — into a human-readable SPEC.md. Deterministic by
// default; `--narrate` adds a one-line LLM description per module.

export interface SpecOptions {
  dir: string;
  adapter: StackAdapter;
  brain?: Brain; // when set, narrate each module
  stamp?: string; // caller-provided timestamp (scripts can't use Date.now)
}

type Graph = Awaited<ReturnType<typeof buildGraph>>;
type Plan = Awaited<ReturnType<typeof buildMockPlan>> | null;
type Cov = Awaited<ReturnType<StackAdapter['coverage']>> | null;

export async function buildSpec(opts: SpecOptions): Promise<string> {
  const { dir, adapter } = opts;
  const graph = await buildGraph(dir);
  const plan = await buildMockPlan(dir).catch(() => null);
  const cov = await adapter.coverage(dir).catch(() => null);
  const name = basename(dir);

  const narratives = opts.brain ? await narrate(opts.brain, graph, adapter, dir) : {};

  const lines: string[] = [];
  lines.push(`# ${name} — Specification`, '');
  lines.push(`_Generated by probevane (${adapter.id})${opts.stamp ? ` on ${opts.stamp}` : ''}._`, '');
  lines.push(...overviewLines(graph, plan, cov));
  lines.push(...graphLines(graph));
  lines.push(...(await modulesLines(graph, narratives, adapter, dir)));
  lines.push(...apiLines(plan));

  return lines.join('\n');
}

/** The `## Overview` section: graph summary, endpoint count, coverage. */
function overviewLines(graph: Graph, plan: Plan, cov: Cov): string[] {
  const lines: string[] = ['## Overview', ''];
  lines.push(`- ${graphSummary(graph)}`);
  if (plan?.handlers.length) lines.push(`- ${plan.handlers.length} network endpoint(s)`);
  if (cov?.ok) lines.push(`- test coverage: ${cov.statements}% statements, ${cov.branches}% branches`);
  lines.push('');
  return lines;
}

/** The `## Module graph` section: ASCII tree + mermaid. */
function graphLines(graph: Graph): string[] {
  // Big graphs: collapse ubiquitous hubs (imported by >=8) so the tree isn't
  // drowned in repeated shared-module leaves — they're listed once in a footer.
  const ascii = toAscii(graph, graph.nodes.size > 40 ? { collapseHubs: 8 } : undefined);
  return ['## Module graph', '', '```', ascii, '```', '', toMermaid(graph), ''];
}

/** One `### path` module section: header, narrative, deps, probe facts. */
async function moduleSection(
  path: string,
  graph: Graph,
  narratives: Record<string, string>,
  adapter: StackAdapter,
  dir: string,
): Promise<string[]> {
  const n = graph.nodes.get(path)!;
  const lines: string[] = [`### ${path} — ${n.kind}${n.callsNetwork ? ' 🌐' : ''}`];
  if (narratives[path]) lines.push('', narratives[path]);
  const deps = n.imports.filter((d) => graph.nodes.has(d));
  if (deps.length) lines.push('', `- depends on: ${deps.join(', ')}`);
  const probe = await adapter.probe(dir, { kind: 'unit', sourcePath: path, name: path.split('/').pop()!.replace(/\.\w+$/, '') });
  if (probe.ok && probe.digest) {
    const facts = probe.digest.split('\n').slice(1).filter((l) => l.trim().startsWith('-'));
    if (facts.length) lines.push('', ...facts.map((f) => `  ${f.trim()}`));
  }
  lines.push('');
  return lines;
}

/** The `## Modules` section (leaf-first, the build/chain order). */
async function modulesLines(
  graph: Graph,
  narratives: Record<string, string>,
  adapter: StackAdapter,
  dir: string,
): Promise<string[]> {
  const lines: string[] = ['## Modules', ''];
  for (const path of graph.order) {
    lines.push(...(await moduleSection(path, graph, narratives, adapter, dir)));
  }
  return lines;
}

/** The `## API surface` section (empty when there are no handlers). */
function apiLines(plan: Plan): string[] {
  if (!plan?.handlers.length) return [];
  const lines: string[] = ['## API surface', ''];
  for (const h of plan.handlers) lines.push(`- \`${h.method} ${h.urlPattern}\``);
  lines.push('');
  return lines;
}

/** Parse `path: sentence` lines from a model reply into the narratives map. */
function parseNarratives(
  text: string,
  graph: Awaited<ReturnType<typeof buildGraph>>,
  out: Record<string, string>,
): void {
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*([^\s:]+):\s*(.+)$/);
    if (m && graph.nodes.has(m[1])) out[m[1]] = m[2].trim();
  }
}

async function narrate(
  brain: Brain,
  graph: Awaited<ReturnType<typeof buildGraph>>,
  adapter: StackAdapter,
  dir: string,
): Promise<Record<string, string>> {
  // Gather each module's probe digest, ask for a one-line description each.
  const digests: string[] = [];
  for (const path of graph.order) {
    const probe = await adapter.probe(dir, { kind: 'unit', sourcePath: path, name: path });
    digests.push(`${path} (${graph.nodes.get(path)!.kind}):\n${probe.digest}`);
  }
  const sys = 'You document codebases. For each module below, write ONE concise sentence describing its responsibility. Reply as lines `path: sentence`, nothing else.';
  const out: Record<string, string> = {};
  // Chunk the modules: one batched call for all of them overruns the model's
  // output cap (~4k tokens) and only the first ~40 get described. Smaller batches
  // keep every response complete, so every module is narrated.
  const CHUNK = 25;
  for (let i = 0; i < digests.length; i += CHUNK) {
    const resp = await brain
      .complete({ system: sys, messages: [{ role: 'user', text: digests.slice(i, i + CHUNK).join('\n\n') }], tools: [] })
      .catch(() => null);
    if (resp?.text) parseNarratives(resp.text, graph, out);
  }
  return out;
}
